'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.4952
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Zulassung

    Partial Public Class Change01_3

        '''<summary>
        '''lnkFahrzeugsuche-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lnkFahrzeugsuche As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkFahrzeugauswahl-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lnkFahrzeugauswahl As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblHead-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UP1-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents UP1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''Hidden1-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents Hidden1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Panel1-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''trErrorSearch-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents trErrorSearch As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblErrorSearch-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lblErrorSearch As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtName-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPLZ-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtPLZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtOrt-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtOrt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSuchen-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents btnSuchen As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''drpAdresse-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents drpAdresse As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lbCancel-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lbCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbGet-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lbGet As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlHalter-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents pnlHalter As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''trError-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents trError As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblError-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMessage-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtShName-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtShName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ibtRefresh-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents ibtRefresh As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ibtSearchLN-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents ibtSearchLN As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''txtShName2-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtShName2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtShStrasse-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtShStrasse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtShPLZ-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtShPLZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtShOrt-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtShOrt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpShLand-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents drpShLand As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlZulDaten-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents pnlZulDaten As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtZulassungsdatum-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtZulassungsdatum As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZulassungsdatum_CE-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtZulassungsdatum_CE As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''cv_txtZulassungsdatum-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents cv_txtZulassungsdatum As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''txtZulkreis-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtZulkreis As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnZulkreis-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents btnZulkreis As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''trWunschkennz-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents trWunschkennz As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''txtWKennzeichen1-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtWKennzeichen1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtWKennzeichen2-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtWKennzeichen2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtWKennzeichen3-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtWKennzeichen3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtResNr-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtResNr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtResName-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtResName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trWunschInfo-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents trWunschInfo As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tr_Zulassungsart-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents tr_Zulassungsart As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ddlZulassungsart-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents ddlZulassungsart As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkFeinstaub-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkFeinstaub As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkTagesul-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents chkTagesul As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TextBox1-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlVersicherer-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents pnlVersicherer As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''CV_EVB-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents CV_EVB As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''txtVersGesellschaft-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVersGesellschaft As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEVBNummer-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtEVBNummer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ibtSearchEVB-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents ibtSearchEVB As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''txtEVBVon-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtEVBVon As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEVBVonCE-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtEVBVonCE As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''txtEVBBis-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtEVBBis As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEVBBisCE-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtEVBBisCE As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''CV_txtEVBVon-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents CV_txtEVBVon As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''CV_txtEVBBis-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents CV_txtEVBBis As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''txtVersNehmer-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVersNehmer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ibtSearchVersicherer-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents ibtSearchVersicherer As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''txtVersStrasse-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVersStrasse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtVersPLZ-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVersPLZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtVersOrt-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVersOrt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpVersLand-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents drpVersLand As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlVSS-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents pnlVSS As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtVssName1-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVssName1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ibtSearchVSS-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents ibtSearchVSS As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''txtVssName2-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVssName2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtVssStrasse-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVssStrasse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtVssPLZ-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVssPLZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtVssOrt-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents txtVssOrt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpVSSLand-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents drpVSSLand As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdSearch-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents cmdSearch As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''btnFake-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents btnFake As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''MPEZulDate-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents MPEZulDate As Global.AjaxControlToolkit.ModalPopupExtender

        '''<summary>
        '''mb-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents mb As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessagePopUp-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents lblMessagePopUp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnYes-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents btnYes As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNo-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents btnNo As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''AniHalter-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents AniHalter As Global.AjaxControlToolkit.AnimationExtender

        '''<summary>
        '''AniVersicherer-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents AniVersicherer As Global.AjaxControlToolkit.AnimationExtender

        '''<summary>
        '''AniVSS-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents AniVSS As Global.AjaxControlToolkit.AnimationExtender

        '''<summary>
        '''AniEVB-Steuerelement
        '''</summary>
        '''<remarks>
        '''Automatisch generiertes Feld
        '''Um dies zu ändern, verschieben Sie die Felddeklaration aus der Designerdatei in eine Code-Behind-Datei.
        '''</remarks>
        Protected WithEvents AniEVB As Global.AjaxControlToolkit.AnimationExtender
    End Class
End Namespace
